# params.yaml
data_split:
  test_size: 0.2
  random_state: 42

training:
  cv_folds: 5
  # Class imbalance handling: 'smote', 'class_weight', or None
  imbalance_handler: 'smote'

# --- Model Hyperparameters & Tuning Grids ---

xgboost:
  static_params:
    objective: 'binary:logistic'
    eval_metric: 'aucpr'
    use_label_encoder: False
  param_grid:
    n_estimators: [100, 200]
    max_depth: [3, 5]
    learning_rate: [0.05, 0.1]

lightgbm:
  static_params:
    objective: 'binary'
    metric: 'aucpr'
  param_grid:
    n_estimators: [100, 200]
    num_leaves: [20, 31]
    learning_rate: [0.05, 0.1]

logistic_regression:
  static_params:
    solver: 'liblinear'
    max_iter: 200
  param_grid:
    C: [0.1, 1.0, 10.0]