# config/config.yaml
data_source:
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  raw_data_filename: "fraud_detection.csv"

minio_credentials:
  endpoint_url: "http://minio:9000"
  bucket_name: "fraud-detection"

mlflow_config:
  tracking_uri: "http://mlflow:5000"
  experiment_name: "Fraud-Detection-Experiments" # More generic name
  registered_model_base_name: "FraudDetector" # Base name for registration

artifacts:
  preprocessor_name: "preprocessor.joblib"
  processed_train_name: "train.csv"
  processed_test_name: "test.csv"

features:
  target_column: "label"
  numerical_cols:
    - "amount"
  categorical_cols:
    - "merchant_type"
    - "device_type"
  drop_cols:
    - "transaction_id"