# config/config.yaml
data:
  raw_path: "data/raw/fraud_detection.csv"
  processed_train_path: "data/processed/train.csv"
  processed_test_path: "data/processed/test.csv"
  # As described by the user
  target_column: "label"
  transaction_id_column: "transaction_id"
  numerical_columns: ["amount"]
  categorical_columns: ["merchant_type", "device_type"]

mlflow:
  tracking_uri: "http://127.0.0.1:5000" # Use localhost for local runs connecting to docker
  experiment_name: "Fraud-Detection-Pipeline"
  registered_model_base_name: "FraudDetector"

artifacts:
  preprocessor_name: "preprocessor.joblib"
  model_dir: "saved_models"