# .github/workflows/release-triggered-training.yaml

name: 'Trigger Model Training on Release'

on:
  release:
    types: [created]

jobs:
  train-and-register-model:
    runs-on: ubuntu-latest
    
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      MLFLOW_S3_ENDPOINT_URL: ${{ secrets.MINIO_ENDPOINT_URL }}

    steps:
      - name: '✅ Checkout Repository'
        uses: actions/checkout@v4

      - name: '🐳 Build Docker Image'
        run: docker build -t fraud-detection-pipeline .

      - name: '🚀 Run Model Training in Docker'
        run: |
          # 1. Check if the tag format is correct (contains a '/')
          if [[ "${{ github.ref_name }}" != */* ]]; then
            echo "Error: Release tag '${{ github.ref_name }}' is not in the required 'model-name/version' format."
            exit 1
          fi

          # 2. Extract the model name (the part before the '/')
          MODEL_NAME=$(echo "${{ github.ref_name }}" | cut -d'/' -f1)
          echo "Extracted model name: $MODEL_NAME"

          # 3. Run the Docker container, passing secrets and arguments
          docker run --rm \
            -e MLFLOW_TRACKING_URI \
            -e MLFLOW_TRACKING_USERNAME \
            -e MLFLOW_TRACKING_PASSWORD \
            -e AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY \
            -e MLFLOW_S3_ENDPOINT_URL \
            fraud-detection-pipeline \
            --model "$MODEL_NAME" --use-best-params
          
      - name: '🎉 Training Complete'
        run: echo "Model training and registration complete. Check your MLflow UI."